---
title: "p8105_hw3_ab6169"
author: "Amrutha Banda"
date: "2025-10-03"
output: github_document
---

```{r}
library(tidyverse)
library(janitor)
library(lubridate)

```

## Problem 1 
```{r}
library(p8105.datasets)
data("instacart")
```

Short Description: 

```{r}
aisles_summary= 
  instacart |> 
  count(aisle, sort=TRUE)

aisles_summary |> 
  head(10) #This gives me a table that shows me top 10 aisles with the most ordered items 
```
Comments: 



Making a Plot n>10,000
```{r}
aisles_summary |> 
  filter(n > 10000) |> 
  mutate(aisle = fct_reorder(aisle, n)) |> #shows me aisles based on n (size)
  ggplot(aes(x = aisle, y = n, fill = aisle)) +
  geom_col(show.legend = FALSE) +
  coord_flip() ##flips the long aisle names
  labs(
    title = "Number of Items Ordered by Aisle (>10,000 orders)",
    x = "Aisle",
    y = "Number of Items Ordered"
  )
```
Comments: 



Table of 3 most popular items 
```{r}
instacart |> 
  filter(aisle %in% 
    c("baking ingredients", "dog food care", "packaged vegetables fruits")) |> 
  group_by(aisle, product_name) |>
  summarize(n = n()) |> 
  slice_max(order_by = n, n = 3) |> 
  knitr::kable(digits = 0)
```
Comments: 



Table of Mean Hour of the Day
```{r}
instacart |> 
  filter(product_name %in% c("Pink Lady Apples", "Coffee Ice Cream")) |> 
  group_by(product_name, order_dow) |> 
  summarize(mean_hour = mean(order_hour_of_day)) |> 
  mutate(order_dow = recode(order_dow,
  `0` = "Sun",
  `1` = "Mon", 
  `2` = "Tue",
  `3` = "Wed",
  `4` = "Thu", 
  `5` = "Fri",
  `6` = "Sat")) |> 
  pivot_wider(
    names_from = order_dow,
    values_from = mean_hour ) |> 
  knitr::kable(digits=2) 
               
```
Comments: 


## Problem 2 

Cleaning
```{r}

zipcodes_df= 
  read_csv("data/zipcodes.csv", na = c("NA", ".", "")) |>
  janitor::clean_names() |> 
  select(-state_fips, -file_date) 

zori_df = 
  read_csv("data/zori.csv", na = c("NA", ".", "")) |> 
  janitor::clean_names() |> 
  pivot_longer(
    cols = starts_with("x20"),
    names_to = "date",
    values_to = "zori"
  ) |> 
  rename(
    zip_code= region_name) |> 
  mutate(county_name= str_remove(county_name, " County")) |> 
  rename(county= county_name) |> 
  select(-city, -metro, -region_type, -state_name, -state, ) |> 
  mutate(date = sub("^x", "", date))

#Joined DataFrame
mergezip_df=
  left_join(zipcodes_df, zori_df, by = c("zip_code","county")) 
```


```{r}
mergezip_df = 
  mergezip_df |> 
  mutate(year = as.numeric(substr(date, 1, 4)))
```

